package tgb.cryptoexchange.merchantdetails.details.yolo;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.io.IOException;

@AllArgsConstructor
@Getter
public enum Bank {
    UNKNOWN("unknown", "Неизвестный"),
    SBERBANK("sberbank", "Сбербанк"),
    TINKOFF("tinkoff", "Т-Банк"),
    VTB("vtb", "Банк ВТБ"),
    ALFABANK("alfabank", "АЛЬФА-БАНК"),
    RAIFFEISENBANK("raiffeisenbank", "Райффайзенбанк"),
    BANK_OPEN("bank_open", "Банк ОТКРЫТИЕ"),
    GAZPROMBANK("gazprombank", "Газпромбанк"),
    PROMSVYAZ("promsvyaz", "Промсвязьбанк"),
    SOVKOM("sovkom", "Совкомбанк"),
    ROS_BANK("ros_bank", "РОСБАНК"),
    RSB("rsb", "Банк Русский Стандарт"),
    ABSOLUTE_BANK("absolute_bank", "АКБ Абсолют Банк"),
    HOME_BANK("home_bank", "Хоум кредит"),
    OTP_BANK("otp_bank", "ОТП Банк"),
    URALSIB("uralsib", "БАНК УРАЛСИБ"),
    AK_BARS_BANK("ak_bars_bank", "АК БАРС БАНК"),
    FORA("fora", "АКБ ФОРА-БАНК"),
    ROST_FINANCE("rost_finance", "КБ РостФинанс"),
    OZON("ozon", "Озон Банк (Ozon)"),
    UNISTREAM("unistream", "КБ ЮНИСТРИМ"),
    MTS("mts", "МТС-Банк"),
    TKB("tkb", "ТрансКапиталБанк"),
    POCHTA("pochta", "Почта Банк"),
    RNCB("rncb", "РНКБ Банк"),
    GENBANK("genbank", "ГЕНБАНК"),
    CIFRA("cifra", "Цифра банк"),
    INGO("ingo", "Ингосстрах Банк"),
    SVOI("svoi", "Свой Банк"),
    AVANGARD("avangard", "АКБ АВАНГАРД"),
    RENCREDIT("rencredit", "КБ Ренессанс Кредит"),
    SOLID("solid", "КБ Солидарность"),
    PUCBR("pucbr", "ПУ Банк России"),
    EXPOBANK("expobank", "Экспобанк"),
    APKBANK("apkbank", "КБ АГРОПРОМКРЕДИТ"),
    BKTB("bktb", "Кубаньторгбанк"),
    BYSTROBANK("bystrobank", "БыстроБанк"),
    NICO_BANK("nico-bank", "НИКО-БАНК"),
    OKBANK("okbank", "Банк Объединенный капитал"),
    PSCB("pscb", "Банк ПСКБ"),
    ZARECH("zarech", "Банк Заречье"),
    ZEMSKY("zemsky", "Земский банк"),
    ABR("abr", "АБ РОССИЯ"),
    BKSBANK("bksbank", "БКС Банк"),
    CHELINVEST("chelinvest", "ЧЕЛЯБИНВЕСТБАНК"),
    DATABANK("databank", "Датабанк"),
    DOMRFBANK("domrfbank", "Банк ДОМ.РФ"),
    ENERGOBANK("energobank", "АКБ Энергобанк"),
    FORSHTADT("forshtadt", "АКБ Форштадт"),
    GAZTRANSBANK("gaztransbank", "Газтрансбанк"),
    GEBANK("gebank", "Газэнергобанк"),
    IN_BANK("in-bank", "Инбанк"),
    ITURUPBANK("iturupbank", "Банк ИТУРУП"),
    KBB("kbb", "Кузнецкбизнесбанк"),
    KBHMB("kbhmb", "Хакасский муниципальный банк"),
    KKBANK("kkbank", "КБ Кубань Кредит"),
    KOSHELEV_BANK("koshelev-bank", "КОШЕЛЕВ-БАНК"),
    KREMLINBANK("kremlinbank", "Банк Кремлевский"),
    MARITIMEBANK("maritimebank", "МОРСКОЙ БАНК"),
    MCBANK("mcbank", "БАНК МОСКВА-СИТИ"),
    METALLINVESTBANK("metallinvestbank", "Металлинвестбанк"),
    AKIBANK("akibank", "АКИБАНК"),
    MODULBANK("modulbank", "КБ Модульбанк"),
    MP_BANK("mp-bank", "МП Банк"),
    NKBANK("nkbank", "НК Банк"),
    NORVIKBANK("norvikbank", "Норвик Банк"),
    NOVIKOM("novikom", "Банк НОВИКОМ (НОВИКОМБАНК)"),
    NOVOBANK("novobank", "УКБ Новобанк"),
    NSBANK("nsbank", "НС Банк"),
    ORBANK("orbank", "БАНК ОРЕНБУРГ"),
    CREDITEUROPE("crediteurope", "Кредит Европа Банк (Россия)"),
    PSKB("pskb", "СКБ Приморья Примсоцбанк"),
    REALISTBANK("realistbank", "РЕАЛИСТ БАНК"),
    RESOCREDITBANK("resocreditbank", "Банк РЕСО Кредит"),
    SINKO_BANK("sinko-bank", "КБ СИНКО-БАНК"),
    SOCIUM_BANK("socium-bank", "СОЦИУМ-БАНК"),
    TATSOTSBANK("tatsotsbank", "ТАТСОЦБАНК"),
    TIMERBANK("timerbank", "Тимер Банк"),
    TRANSSTROYBANK("transstroybank", "АКБ Трансстройбанк"),
    AGROS("agros", "Банк Агророс"),
    AKCEPT("akcept", "Банк Акцепт"),
    ALEFBANK("alefbank", "АКБ Алеф-Банк"),
    ARESBANK("aresbank", "КБ АРЕСБАНК"),
    BANCAINTESA("bancaintesa", "Банк Интеза"),
    BANK_HLYNOV("bank-hlynov", "КБ Хлынов"),
    BANKOFKAZAN("bankofkazan", "КБЭР Банк Казани"),
    BSPB("bspb", "Банк Санкт-Петербург"),
    CENTRINVEST("centrinvest", "КБ Центр-инвест"),
    CFB("cfb", "Банк БКФ"),
    CHELINDBANK("chelindbank", "ЧЕЛИНДБАНК"),
    COALMETBANK("coalmetbank", "Углеметбанк"),
    CREDITURAL("creditural", "Кредит Урал Банк"),
    DCAPITAL("dcapital", "Банк Развитие-Столица"),
    DVBANK("dvbank", "Дальневосточный банк"),
    EL_PLAT("el-plat", "ПНКО ЭЛПЛАТ"),
    ENERGOTRANSBANK("energotransbank", "КБ ЭНЕРГОТРАНСБАНК"),
    FINAM("finam", "Банк ФИНАМ"),
    GIBANK("gibank", "КБ Гарант-Инвест"),
    GORBANK("gorbank", "ГОРБАНК"),
    GUTABANK("gutabank", "ГУТА-БАНК"),
    ICBRU("icbru", "ИК Банк"),
    LANTA("lanta", "АКБ Ланта-Банк"),
    LOCKOBANK("lockobank", "КБ ЛОКО-Банк"),
    MCBANKRUS("mcbankrus", "МС Банк Рус"),
    METCOM("metcom", "МЕТКОМБАНК"),
    MSPBANK("mspbank", "МС Примбанк"),
    NIPBANK("nipbank", "Нацинвестпромбанк"),
    NS_BANK("ns-bank", "Банк Национальный стандарт"),
    NSKBL("nskbl", "Банк Левобережный"),
    POIDEM("poidem", "КБ Пойдём"),
    PRIMBANK("primbank", "АКБ Приморье"),
    PROBANK("probank", "ПроБанк"),
    RDB("rdb", "РосДорБанк"),
    SDM("sdm", "СДМ-Банк"),
    SEVNB("sevnb", "Северный Народный Банк"),
    SIBSOC("sibsoc", "СИБСОЦБАНК"),
    SNGB("sngb", "БАНК СНГБ"),
    TAVRICH("tavrich", "Таврический Банк"),
    TENDERBANK("tenderbank", "АКБ ТЕНДЕР-БАНК"),
    THBANK("thbank", "Тольяттихимбанк"),
    TPSBANK("tpsbank", "Томскпромстройбанк"),
    UNICREDITBANK("unicreditbank", "ЮниКредит Банк"),
    URALFD("uralfd", "КБ Урал ФД"),
    VBRR("vbrr", "Банк ВБРР"),
    VENETS_BANK("venets-bank", "Банк Венец"),
    VFBANK("vfbank", "КБ ВНЕШФИНБАНК"),
    ZENIT("zenit", "Банк ЗЕНИТ"),
    YOOMONEY("yoomoney", "НКО ЮМани"),
    AVTOFINBANK("avtofinbank", "Авто Финанс Банк"),
    AVTOTORGBANK("avtotorgbank", "Автоторгбанк"),
    AIKB_ENISEJSKIJ_OBEDINENNYJ_BANK("aikb-enisejskij-obedinennyj-bank", "АИКБ Енисейский объединенный банк"),
    BANK_SINARA("bank-sinara", "Банк Синара"),
    BANK_URALFINANS("bank-uralfinans", "Уралфинанс"),
    BANK_CENTROKREDIT("bank-centrokredit", "ЦентроКредит"),
    IS_BANK("is-bank", "ИС Банк"),
    KB_DOLINSK("kb-dolinsk", "КБ Долинск"),
    NOVYJ_VEK("novyj-vek", "КБ Новый век"),
    UKB_BELGORODSOCBANK("ukb-belgorodsocbank", "УКБ Белгородсоцбанк"),
    AVTOGRADBANK("avtogradbank", "Автоградбанк"),
    BANK_EKATERINBURG("bank-ekaterinburg", "Банк Екатеринбург"),
    BANK_SGB("bank-sgb", "БАНК СГБ"),
    BANK_SIAB("bank-siab", "Банк СИАБ"),
    DZHEJ_JEND_TI_BANK("dzhej-jend-ti-bank", "Джей энд Ти Банк (АО)"),
    MB_BANK("mb-bank", "МБ Банк"),
    SMP_BANK("smp-bank", "СМП Банк"),
    TOCHKA_OTKRYTIE("tochka-otkrytie", "ТОЧКА (ФК Открытие)"),
    BSD_BANK("bsdbank", "Черноморский банк развития"),
    KLOOKVA("klookva", "Клюква"),
    BLANC("blanc", "Бланк банк"),
    TKBBANK("tkbbank", "ТКБ БАНК"),
    NRB("nrb", "АКБ НРБанк"),
    FINSTARBANK("finstarbank", "ФИНСТАР БАНК"),
    ROUND("round", "банк Раунд"),
    DTB1("dtb1", "Первый Дортрансбанк"),
    CMRBANK("cmrbank", "ЦМРБанк"),
    PLAIT("plait", "Плайт"),
    BANKORANGE("bankorange", "Банк Оранжевый"),
    YARINTERBANK("yarinterbank", "ИКБР ЯРИНТЕРБАНК"),
    YANDEXBANK("yandexbank", "Яндекс Банк"),
    BANK_MBA_MOSKVA("bank-mba-moskva", "Банк МБА МОСКВА"),
    BANK_IPB("bank-ipb", "Банк ИПБ"),
    BANK_JELITA("bank-jelita", "банк Элита"),
    BANK_VOLOGZHANIN("bank-vologzhanin", "Банк Вологжанин"),
    DRAJ_KLIK_BANK("drajv-klik-bank", "Драйв Клик Банк"),
    ROSSELHOZBANK("rosselhozbank", "Россельхозбанк"),
    HAJS("hajs", "Хайс"),
    JES_BI_AJ_BANK("jes-bi-aj-bank", "Эс-Би-Ай Банк"),
    RUSNARBANK("rusnarbank", "РУСНАРБАНК"),
    BANK_SARATOV("bank-saratov", "Банк Саратов"),
    PERVYJ_INVESTICIONNYJ_BANK("pervyj-investicionnyj-bank", "Первый Инвестиционный Банк"),
    AKB_DERZHAVA("akb-derzhava", "АКБ Держава"),
    KB_STROJLESBANK("kb-strojlesbank", "КБ Стройлесбанк"),
    TOJOTA_BANK("tojota-bank", "Тойота Банк"),
    KB_MOSKOMMERCBANK("kb-moskommercbank", "КБ Москоммерцбанк"),
    URALPROMBANK("uralprombank", "УРАЛПРОМБАНК"),
    CITIBANK("citibank", "Ситибанк"),
    BANK_ALEKSANDROVSKIJ("bank-aleksandrovskij", "Банк АЛЕКСАНДРОВСКИЙ"),
    MEZHDUNARODNYJ_FINANSOVYJ_KLUB("mezhdunarodnyj-finansovyj-klub", "МЕЖДУНАРОДНЫЙ ФИНАНСОВЫЙ КЛУБ"),
    MKB("mkb", "Московский кредитный банк"),
    NBD_BANK("nbd-bank", "НБД-Банк"),
    NOKSSBANK("nokssbank", "НОКССБАНК"),
    VUZ_BANK("vuz-bank", "ВУЗ-банк"),
    BANK_BZHF("bank-bzhf", "Банк БЖФ"),
    JUG_INVESTBANK("jug-investbank", "ЮГ-Инвестбанк"),
    KB_KROKUS_BANK("kb-krokus-bank", "КБ Крокус Банк"),
    VLADBIZNESBANK("vladbiznesbank", "ВЛАДБИЗНЕСБАНК"),
    BANK_AVERS("bank-avers", "Банк Аверс"),
    WBBANK("wbbank", "Вайлдберриз Банк"),
    ISHBANK("ishbank", "ИШБАНК"),
    ALMAZJERGIJENBANK("almazjergijenbank", "Алмазэргиэнбанк"),
    AZIATSKO_TIHOOKEANSKIJ_BANK("aziatsko-tihookeanskij-bank", "Азиатско-Тихоокеанский Банк"),
    AGROOROS("agroros", "Банк Агророс"),
    BBR_BANK("bbr-bank", "ББР Банк"),
    SOLID_BANK("solid-bank", "Солид Банк"),
    RUS_UNIVERSALBANK("rus-universalbank", "Русьуниверсалбанк"),
    AKB_SLAVIJA("akb-slavija", "АКБ СЛАВИЯ"),
    AKB_EVROFINANS_MOSNARBANK("akb-evrofinans-mosnarbank", "АКБ ЕВРОФИНАНС МОСНАРБАНК"),
    UBRIR("ubrir", "Банк УБРиР"),
    BANK_RAUND("bank-raund", "банк Раунд"),
    TOCHKA_BANK("tochka-bank", "Точка Банк"),
    PRIO_VNESHTORGBANK("prio-vneshtorgbank", "Прио-Внешторгбанк"),
    BANK_SNEZHINSKIJ("bank-snezhinskij", "Банк Снежинский"),
    MOSKOMBANK("moskombank", "МОСКОМБАНК"),
    STAVRPROMSTROI("stavrpromstroi", "Ставропольпромстрой банк"),
    DUSHANBE_CITY("dushanbe_city", "Душанбе сити"),
    ALIF("alif", "Алиф"),
    ESKHATA("eskhata", "Эсхата"),
    SPITAMEN("spitamen", "Спитамен"),
    VASL("vasl", "Васл"),
    IMON("imon", "Имон"),
    MATIN("matin", "Матин"),
    SSB("ssb", "Ссб"),
    INTERNATIONAL_BANK_TAJIKISTAN("international_bank_tajikistan", "Международный банк Таджикистана"),
    ORIEN("orien", "Ориен"),
    AURORA("aurora", "АВРОРА"),
    PSB("psb", "Банк ПСБ"),
    BEELINE("beeline", "Билайн"),
    CUPIS("cupis", "Цупис"),
    AVITO("avito", "Авито"),
    MTSDENGI("mtsdengi", "МТС Деньги"),
    ROCKET("rocket", "Рокетбанк"),
    ODENGI("odengi", "ОДеньги"),
    AZIANPACIFICOCEANBANK("azianpacificoceanbank", "Азиатско-Тихоокеанский банк"),
    VAILDBERRIZBANK("vaildberrizbank", "Вайлдберриз Банк"),
    VASL_BANK("vasl.bank", "Vasl Bank"),
    SPITAMEN_BANK("spitamen.bank", "Спитамен Банк"),
    AMONAT_BANK("amonat.bank", "Amonat Bank"),
    QPLUS("qplus", "qplus"),
    PERMATA_BANK("permata.bank", "Permata Bank");

    private final String code;

    private final String displayName;

    public static String bankNameFromCode(String value) {
        for (Bank bank : Bank.values()) {
            if (bank.code.equals(value)) {
                return bank.getDisplayName();
            }
        }
        return value;
    }

    public static class Deserializer extends JsonDeserializer<String> {
        @Override
        public String deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws IOException {
            return Bank.bankNameFromCode(jsonParser.getValueAsString());
        }
    }
}
